---
title: "R and Python in RStudio"
author: "Harald Hofer"
date: "3 3 2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



This is a good brief into for using Python in RStudio:

https://rstudio.github.io/reticulate/articles/r_markdown.html


This is also great and more detailed:

https://resources.github.com/whitepapers/github-and-rstudio/



## R Code

```{r message = FALSE, warning = FALSE}
library(tidyverse)
```

```{r}
cars %>%
  ggplot(aes(x = speed, y = dist)) +
    stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE, interpolate = TRUE) +
    geom_point(color = "white", alpha = 0.5, size = 1) +
    scale_fill_continuous(type = "viridis") +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    theme_minimal()
```



## Python code
```{r}
# install.packages("reticulate") # if not installed
library(reticulate)
use_python("C:/Users/hhofer01/AppData/Local/Continuum/anaconda3/")
```


To access objects (from default R or) created in R-chunks use "r." as prefix

```{python}
import os
os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] = "C:/Users/hhofer01/AppData/Local/Continuum/anaconda3/Library/plugins/platforms" # Add this so all libraries needed for knitting get found during knitting

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
```

```{python}
# change "r" in chunk-header to "python
print(r.cars.head())
py_cars = r.cars * 1.9
```

```{python}
sns.set(style = "ticks")
sns.jointplot(x = r.cars["speed"], y = r.cars["dist"], kind = "hex")
plt.show()
```



To access Python-objects in R-chunks use "py$" as prefix. Indexing works like in R.

```{r}
hist(py$py_cars[, 1], breaks = 7, col = "deepskyblue")
```

